### ISSUE TITLE
org header in documentation

### ISSUE THREAD

**Issue by dreddymon** [abrochard/org-sync-snippets#3]
https://github.com/abrochard/org-sync-snippets/blob/0f264a032d371d7dbb4a7cbaf0ea2f91b5a629ca/org-sync-snippets.el#L56

use `:tangle no` instead of `tangle: no`

**Comment by abrochard** [comment]
Thank you for your interest!
I think that this might be a misunderstanding. The purpose of the `tangle: no` header is to prevent exporting to org sensitive snippets. In that sense, it is not an org header but a yasnippet header which does follow the format `key: value` (for reference, [an excellent snippet repo ](https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/c-mode/printf)).
What you seem to be proposing is the org style header `:key value`, which is not appropriate in a yasnippet file.
