### ISSUE TITLE
Tangle Snippet

### ISSUE THREAD

**Issue by arkhan** [abrochard/org-sync-snippets#4]
hello,

Greate work.

I have the following problem:

In my ORG file I have this:
``` orgmode
* python-mode

** odoo_class
#+BEGIN_SRC snippet :tangle {SNIPPETS-DIR}/python-mode/odoo_class
  # name: Odoo New Class
  # key: onc
  # --
  class ${1:ClassName}(models.${2:class_type}):
      """
      ${3:docstring}
      """

      _name = "${4:class.name}"
      _description = __doc__

      $0
#+END_SRC
```
But when I run **org-sync-snippets-org-to-snippets**, the snippet is not created

Thanks

**Comment by abrochard** [comment]
Hi,
Thank you for using my package.

- Did this ever work? Do you see an error message wen you run `org-sync-snippets-org-to-snippets`?
- Where is this org file located? Is it under `~/org/snippets.org`? Do you have your `org-directory` variable set?
- Have you checked the `~/.emacs.d/snippets/` folder for the snippet? Or is it just not loaded into yasnippet?

**Comment by arkhan** [comment]
Hello,

- At the moment of executing **org-sync-snippets-org-to-snippets** it does not give me any error.

- I am using the default configuration.

- The following happens: 

When the snippet in the org file looks like this:
```
* python-mode

** odoo_class
#+BEGIN_SRC snippet :tangle {SNIPPETS-DIR}/python-mode/odoo_class
  # name: Odoo New Class
  # key: onc
  # --
  class ${1:ClassName}(models.${2:class_type}):
      """
      ${3:docstring}
      """

      _name = "${4:class.name}"
      _description = __doc__

      $0
#+END_SRC
```
does not generate the snippet

but if this one like this:

```
* python-mode

** odoo_class
#+BEGIN_SRC snippet :tangle {SNIPPETS-DIR}/python-mode/odoo_class
  # name: Odoo New Class
  # key: onc
  # --
  class ${1:ClassName}(models.${2:class_type}):
      """
      ${3:docstring}
      """

      _name = "${4:class.name}"
      _description = __doc__
#+END_SRC
```
generates the snippet without problems

Apparently it is a problem when the SRC block ends with $0 or with blanks

**Comment by abrochard** [comment]
Thank you that was very helpful. I just pushed a fix for the regex that matches the code blocks and tested with the snippet you provided. Melpa should pick it up and build it within the day. Let me know if it works.

**Comment by arkhan** [comment]
great thank you very much
