### ISSUE TITLE
Regex demands snippet to be indented

### ISSUE THREAD

**Issue by PauloPhagula** [abrochard/org-sync-snippets#5]
First of, thanks for this great package. It is a life-saver.

Secondly, I've found that this regex https://github.com/abrochard/org-sync-snippets/blob/50cefe5a37196ed1af3d330d6871c3b37fa90d41/org-sync-snippets.el#L162

demands that the snippet be indented, making for this first example to be export into the snippets folder

```org
#+BEGIN_SRC snippet :tangle {SNIPPETS-DIR}/js2-mode/console.log
	  # -*- mode: snippet -*-
	  # name: console.log
	  # key: log
	  # --
	  console.log($1);
#+END_SRC
```

but not this second one

```org
#+BEGIN_SRC snippet :tangle {SNIPPETS-DIR}/js2-mode/console.log
# -*- mode: snippet -*-
# name: console.log
# key: log
# --
console.log($1);
#+END_SRC
```

This is an unexpected behavior since the second example is also a valid way of writing src blocks, and also -- at least to me -- the one that gives me proper syntax highlighting since I've set `org-edit-src-content-indentation` to `0`.

Could you please change the regex as to just take whatever content is within `BEGIN_SRC` and `END_SRC` regardless of the indentation?

**Comment by abrochard** [comment]
Thank you! Feel free to re-open if that didn't fix.

**Comment by PauloPhagula** [comment]
Unfortunately the change did not fix the issue. Please reopen

**Comment by abrochard** [comment]
Did you load directly from code or MELPA? It can take a few hours for a new version to hit MELPA.

**Comment by PauloPhagula** [comment]
I'm using quelpa to load the code straight from GitHub. And I've read the code. Its the latest with the last commit

**Comment by abrochard** [comment]
Ok I just made another push and wrote a little unit test for it. Let me know.

**Comment by PauloPhagula** [comment]
It's working now. Thank you very much 👍🏿
